Added Hindi locale
B0und/WikiSpeedrun pull request #27
Opened 2024-05-14 12:20 UTC by Prasanta-Hembram

Added Hindi locale

2024-05-18 17:13 UTC, B0und requested changes

2024-05-18 17:13 UTC, B0und commented on src/i18n/hi/index.ts
> +    description: "Complete your first speedrun",
missed one

2024-05-22 07:53 UTC, Prasanta-Hembram commented on src/i18n/hi/index.ts
> +    description: "Complete your first speedrun",
translated the missing strings.

2024-05-24 16:44 UTC, B0und approved these changes
Thanks for your help

2024-05-24 16:45 UTC, merged